/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Bank account information
 */
@ApiModel(description = "Bank account information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-08T15:06:38.927Z")
public class BankAccountInput {
  @SerializedName("name")
  private String name = null;

  @SerializedName("bank_name")
  private String bankName = null;

  @SerializedName("currency_code")
  private String currencyCode = null;

  @SerializedName("swift")
  private String swift = null;

  @SerializedName("iban")
  private String iban = null;

  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("address3")
  private String address3 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("state_county")
  private String stateCounty = null;

  @SerializedName("zip_postcode")
  private String zipPostcode = null;

  @SerializedName("country_name")
  private String countryName = null;

  @SerializedName("contact_name")
  private String contactName = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("website")
  private String website = null;

  public BankAccountInput name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BankAccountInput bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public BankAccountInput currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public BankAccountInput swift(String swift) {
    this.swift = swift;
    return this;
  }

   /**
   * Get swift
   * @return swift
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSwift() {
    return swift;
  }

  public void setSwift(String swift) {
    this.swift = swift;
  }

  public BankAccountInput iban(String iban) {
    this.iban = iban;
    return this;
  }

   /**
   * Get iban
   * @return iban
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIban() {
    return iban;
  }

  public void setIban(String iban) {
    this.iban = iban;
  }

  public BankAccountInput address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Get address1
   * @return address1
  **/
  @ApiModelProperty(value = "")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public BankAccountInput address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Get address2
   * @return address2
  **/
  @ApiModelProperty(value = "")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public BankAccountInput address3(String address3) {
    this.address3 = address3;
    return this;
  }

   /**
   * Get address3
   * @return address3
  **/
  @ApiModelProperty(value = "")
  public String getAddress3() {
    return address3;
  }

  public void setAddress3(String address3) {
    this.address3 = address3;
  }

  public BankAccountInput city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public BankAccountInput stateCounty(String stateCounty) {
    this.stateCounty = stateCounty;
    return this;
  }

   /**
   * Get stateCounty
   * @return stateCounty
  **/
  @ApiModelProperty(value = "")
  public String getStateCounty() {
    return stateCounty;
  }

  public void setStateCounty(String stateCounty) {
    this.stateCounty = stateCounty;
  }

  public BankAccountInput zipPostcode(String zipPostcode) {
    this.zipPostcode = zipPostcode;
    return this;
  }

   /**
   * Get zipPostcode
   * @return zipPostcode
  **/
  @ApiModelProperty(value = "")
  public String getZipPostcode() {
    return zipPostcode;
  }

  public void setZipPostcode(String zipPostcode) {
    this.zipPostcode = zipPostcode;
  }

  public BankAccountInput countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

   /**
   * Get countryName
   * @return countryName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  public BankAccountInput contactName(String contactName) {
    this.contactName = contactName;
    return this;
  }

   /**
   * Get contactName
   * @return contactName
  **/
  @ApiModelProperty(value = "")
  public String getContactName() {
    return contactName;
  }

  public void setContactName(String contactName) {
    this.contactName = contactName;
  }

  public BankAccountInput phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public BankAccountInput email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public BankAccountInput website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @ApiModelProperty(value = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountInput bankAccountInput = (BankAccountInput) o;
    return Objects.equals(this.name, bankAccountInput.name) &&
        Objects.equals(this.bankName, bankAccountInput.bankName) &&
        Objects.equals(this.currencyCode, bankAccountInput.currencyCode) &&
        Objects.equals(this.swift, bankAccountInput.swift) &&
        Objects.equals(this.iban, bankAccountInput.iban) &&
        Objects.equals(this.address1, bankAccountInput.address1) &&
        Objects.equals(this.address2, bankAccountInput.address2) &&
        Objects.equals(this.address3, bankAccountInput.address3) &&
        Objects.equals(this.city, bankAccountInput.city) &&
        Objects.equals(this.stateCounty, bankAccountInput.stateCounty) &&
        Objects.equals(this.zipPostcode, bankAccountInput.zipPostcode) &&
        Objects.equals(this.countryName, bankAccountInput.countryName) &&
        Objects.equals(this.contactName, bankAccountInput.contactName) &&
        Objects.equals(this.phone, bankAccountInput.phone) &&
        Objects.equals(this.email, bankAccountInput.email) &&
        Objects.equals(this.website, bankAccountInput.website);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, bankName, currencyCode, swift, iban, address1, address2, address3, city, stateCounty, zipPostcode, countryName, contactName, phone, email, website);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountInput {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    swift: ").append(toIndentedString(swift)).append("\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    address3: ").append(toIndentedString(address3)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateCounty: ").append(toIndentedString(stateCounty)).append("\n");
    sb.append("    zipPostcode: ").append(toIndentedString(zipPostcode)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    contactName: ").append(toIndentedString(contactName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

