/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.8
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * PayablesLedger
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-08T15:31:30.205Z")
public class PayablesLedger {
  @SerializedName("date")
  private LocalDate date = null;

  @SerializedName("ledger_type")
  private String ledgerType = null;

  @SerializedName("narrative")
  private String narrative = null;

  @SerializedName("amount")
  private Double amount = null;

  @SerializedName("reconciled")
  private Boolean reconciled = null;

  @SerializedName("journal_id")
  private Long journalId = null;

  @SerializedName("sales_invoice_id")
  private Long salesInvoiceId = null;

  public PayablesLedger date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(required = true, value = "")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

  public PayablesLedger ledgerType(String ledgerType) {
    this.ledgerType = ledgerType;
    return this;
  }

   /**
   * Get ledgerType
   * @return ledgerType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLedgerType() {
    return ledgerType;
  }

  public void setLedgerType(String ledgerType) {
    this.ledgerType = ledgerType;
  }

  public PayablesLedger narrative(String narrative) {
    this.narrative = narrative;
    return this;
  }

   /**
   * Get narrative
   * @return narrative
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNarrative() {
    return narrative;
  }

  public void setNarrative(String narrative) {
    this.narrative = narrative;
  }

  public PayablesLedger amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }

  public PayablesLedger reconciled(Boolean reconciled) {
    this.reconciled = reconciled;
    return this;
  }

   /**
   * Get reconciled
   * @return reconciled
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean isReconciled() {
    return reconciled;
  }

  public void setReconciled(Boolean reconciled) {
    this.reconciled = reconciled;
  }

  public PayablesLedger journalId(Long journalId) {
    this.journalId = journalId;
    return this;
  }

   /**
   * Get journalId
   * @return journalId
  **/
  @ApiModelProperty(value = "")
  public Long getJournalId() {
    return journalId;
  }

  public void setJournalId(Long journalId) {
    this.journalId = journalId;
  }

  public PayablesLedger salesInvoiceId(Long salesInvoiceId) {
    this.salesInvoiceId = salesInvoiceId;
    return this;
  }

   /**
   * Get salesInvoiceId
   * @return salesInvoiceId
  **/
  @ApiModelProperty(value = "")
  public Long getSalesInvoiceId() {
    return salesInvoiceId;
  }

  public void setSalesInvoiceId(Long salesInvoiceId) {
    this.salesInvoiceId = salesInvoiceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayablesLedger payablesLedger = (PayablesLedger) o;
    return Objects.equals(this.date, payablesLedger.date) &&
        Objects.equals(this.ledgerType, payablesLedger.ledgerType) &&
        Objects.equals(this.narrative, payablesLedger.narrative) &&
        Objects.equals(this.amount, payablesLedger.amount) &&
        Objects.equals(this.reconciled, payablesLedger.reconciled) &&
        Objects.equals(this.journalId, payablesLedger.journalId) &&
        Objects.equals(this.salesInvoiceId, payablesLedger.salesInvoiceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, ledgerType, narrative, amount, reconciled, journalId, salesInvoiceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayablesLedger {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    ledgerType: ").append(toIndentedString(ledgerType)).append("\n");
    sb.append("    narrative: ").append(toIndentedString(narrative)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    reconciled: ").append(toIndentedString(reconciled)).append("\n");
    sb.append("    journalId: ").append(toIndentedString(journalId)).append("\n");
    sb.append("    salesInvoiceId: ").append(toIndentedString(salesInvoiceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

