/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.8
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Production Order Details
 */
@ApiModel(description = "Production Order Details")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-08T15:31:30.205Z")
public class ProductionOrderInput {
  @SerializedName("priority")
  private Integer priority = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("notes")
  private String notes = null;

  @SerializedName("bill_of_materials_id")
  private Long billOfMaterialsId = null;

  @SerializedName("sales_order_id")
  private Long salesOrderId = null;

  public ProductionOrderInput priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public ProductionOrderInput quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public ProductionOrderInput notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @ApiModelProperty(value = "")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public ProductionOrderInput billOfMaterialsId(Long billOfMaterialsId) {
    this.billOfMaterialsId = billOfMaterialsId;
    return this;
  }

   /**
   * Get billOfMaterialsId
   * @return billOfMaterialsId
  **/
  @ApiModelProperty(value = "")
  public Long getBillOfMaterialsId() {
    return billOfMaterialsId;
  }

  public void setBillOfMaterialsId(Long billOfMaterialsId) {
    this.billOfMaterialsId = billOfMaterialsId;
  }

  public ProductionOrderInput salesOrderId(Long salesOrderId) {
    this.salesOrderId = salesOrderId;
    return this;
  }

   /**
   * Get salesOrderId
   * @return salesOrderId
  **/
  @ApiModelProperty(value = "")
  public Long getSalesOrderId() {
    return salesOrderId;
  }

  public void setSalesOrderId(Long salesOrderId) {
    this.salesOrderId = salesOrderId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductionOrderInput productionOrderInput = (ProductionOrderInput) o;
    return Objects.equals(this.priority, productionOrderInput.priority) &&
        Objects.equals(this.quantity, productionOrderInput.quantity) &&
        Objects.equals(this.notes, productionOrderInput.notes) &&
        Objects.equals(this.billOfMaterialsId, productionOrderInput.billOfMaterialsId) &&
        Objects.equals(this.salesOrderId, productionOrderInput.salesOrderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(priority, quantity, notes, billOfMaterialsId, salesOrderId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductionOrderInput {\n");
    
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    billOfMaterialsId: ").append(toIndentedString(billOfMaterialsId)).append("\n");
    sb.append("    salesOrderId: ").append(toIndentedString(salesOrderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

