/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BankAccount;
import io.swagger.client.model.BankAccountInput;
import io.swagger.client.model.ErrorModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BankAccountApi
 */
@Ignore
public class BankAccountApiTest {

    private final BankAccountApi api = new BankAccountApi();

    
    /**
     * 
     *
     * Creates a new bank account in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addBankAccountTest() throws ApiException {
        BankAccountInput bankAccount = null;
        BankAccount response = api.addBankAccount(bankAccount);

        // TODO: test validations
    }
    
    /**
     * Find Bank Account by ID
     *
     * Returns a single bank account if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findBankAccountByIdTest() throws ApiException {
        Long id = null;
        BankAccount response = api.findBankAccountById(id);

        // TODO: test validations
    }
    
    /**
     * All bank accounts
     *
     * Returns all bank accounts from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findBankAccountsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<BankAccount> response = api.findBankAccounts(tags, limit);

        // TODO: test validations
    }
    
}
