/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BillOfMaterial;
import io.swagger.client.model.BillOfMaterialInput;
import io.swagger.client.model.ErrorModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BillOfMaterialsApi
 */
@Ignore
public class BillOfMaterialsApiTest {

    private final BillOfMaterialsApi api = new BillOfMaterialsApi();

    
    /**
     * 
     *
     * Creates a new bill of materials in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addBillOfMaterialTest() throws ApiException {
        BillOfMaterialInput billOfMaterials = null;
        BillOfMaterial response = api.addBillOfMaterial(billOfMaterials);

        // TODO: test validations
    }
    
    /**
     * Find Bill of Materials by ID
     *
     * Returns a single bill of materials if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findBillOfMaterialByIdTest() throws ApiException {
        Long id = null;
        BillOfMaterial response = api.findBillOfMaterialById(id);

        // TODO: test validations
    }
    
    /**
     * All bill of materials
     *
     * Returns all bill of materials from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findBillOfMaterialsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<BillOfMaterial> response = api.findBillOfMaterials(tags, limit);

        // TODO: test validations
    }
    
}
