/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Company;
import io.swagger.client.model.ErrorModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompanyApi
 */
@Ignore
public class CompanyApiTest {

    private final CompanyApi api = new CompanyApi();

    
    /**
     * Find Company details by ID
     *
     * Returns a single company details if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findCompanyByIdTest() throws ApiException {
        Long id = null;
        Company response = api.findCompanyById(id);

        // TODO: test validations
    }
    
}
