/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Document;
import io.swagger.client.model.DocumentInput;
import io.swagger.client.model.ErrorModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentApi
 */
@Ignore
public class DocumentApiTest {

    private final DocumentApi api = new DocumentApi();

    
    /**
     * 
     *
     * Creates a new document in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addDocumentTest() throws ApiException {
        DocumentInput documents = null;
        Document response = api.addDocument(documents);

        // TODO: test validations
    }
    
    /**
     * Find Document by ID
     *
     * Returns a single document if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findDocumentByIdTest() throws ApiException {
        Long id = null;
        Document response = api.findDocumentById(id);

        // TODO: test validations
    }
    
    /**
     * All document
     *
     * Returns all document from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findDocumentsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<Document> response = api.findDocuments(tags, limit);

        // TODO: test validations
    }
    
}
