/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.Image;
import io.swagger.client.model.ImageInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImageApi
 */
@Ignore
public class ImageApiTest {

    private final ImageApi api = new ImageApi();

    
    /**
     * 
     *
     * Creates a new image in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addImageTest() throws ApiException {
        ImageInput images = null;
        Image response = api.addImage(images);

        // TODO: test validations
    }
    
    /**
     * Find Image by ID
     *
     * Returns a single image if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findImageByIdTest() throws ApiException {
        Long id = null;
        Image response = api.findImageById(id);

        // TODO: test validations
    }
    
    /**
     * All image
     *
     * Returns all image from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findImagesTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<Image> response = api.findImages(tags, limit);

        // TODO: test validations
    }
    
}
