/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.Journal;
import io.swagger.client.model.JournalInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JournalApi
 */
@Ignore
public class JournalApiTest {

    private final JournalApi api = new JournalApi();

    
    /**
     * 
     *
     * Creates a new journal in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addJournalTest() throws ApiException {
        JournalInput journals = null;
        Journal response = api.addJournal(journals);

        // TODO: test validations
    }
    
    /**
     * Find Journal by ID
     *
     * Returns a single journal if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findJournalByIdTest() throws ApiException {
        Long id = null;
        Journal response = api.findJournalById(id);

        // TODO: test validations
    }
    
    /**
     * All journal
     *
     * Returns all journal from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findJournalsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<Journal> response = api.findJournals(tags, limit);

        // TODO: test validations
    }
    
}
