/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.NominalAccount;
import io.swagger.client.model.NominalAccountInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NominalAccountApi
 */
@Ignore
public class NominalAccountApiTest {

    private final NominalAccountApi api = new NominalAccountApi();

    
    /**
     * 
     *
     * Creates a new nominal account in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addNominalAccountTest() throws ApiException {
        NominalAccountInput nominalAccounts = null;
        NominalAccount response = api.addNominalAccount(nominalAccounts);

        // TODO: test validations
    }
    
    /**
     * Find Nominal account by ID
     *
     * Returns a single nominal account if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findNominalAccountByIdTest() throws ApiException {
        Long id = null;
        NominalAccount response = api.findNominalAccountById(id);

        // TODO: test validations
    }
    
    /**
     * All nominal account
     *
     * Returns all nominal account from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findNominalAccountsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<NominalAccount> response = api.findNominalAccounts(tags, limit);

        // TODO: test validations
    }
    
}
