/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.PartnerAddress;
import io.swagger.client.model.PartnerAddressInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PartnerAddressApi
 */
@Ignore
public class PartnerAddressApiTest {

    private final PartnerAddressApi api = new PartnerAddressApi();

    
    /**
     * 
     *
     * Creates a new partner address in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPartnerAddressTest() throws ApiException {
        PartnerAddressInput partnerAddresses = null;
        PartnerAddress response = api.addPartnerAddress(partnerAddresses);

        // TODO: test validations
    }
    
    /**
     * Find Partner address by ID
     *
     * Returns a single partner address if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findPartnerAddressByIdTest() throws ApiException {
        Long id = null;
        PartnerAddress response = api.findPartnerAddressById(id);

        // TODO: test validations
    }
    
    /**
     * All partner address
     *
     * Returns all partner address from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findPartnerAddressesTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<PartnerAddress> response = api.findPartnerAddresses(tags, limit);

        // TODO: test validations
    }
    
}
