/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.Product;
import io.swagger.client.model.ProductInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductApi
 */
@Ignore
public class ProductApiTest {

    private final ProductApi api = new ProductApi();

    
    /**
     * 
     *
     * Creates a new product in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addProductTest() throws ApiException {
        ProductInput products = null;
        Product response = api.addProduct(products);

        // TODO: test validations
    }
    
    /**
     * Find Product by ID
     *
     * Returns a single product if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findProductByIdTest() throws ApiException {
        Long id = null;
        Product response = api.findProductById(id);

        // TODO: test validations
    }
    
    /**
     * All product
     *
     * Returns all product from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findProductsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<Product> response = api.findProducts(tags, limit);

        // TODO: test validations
    }
    
}
