/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.ProductionOrder;
import io.swagger.client.model.ProductionOrderInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductionOrderApi
 */
@Ignore
public class ProductionOrderApiTest {

    private final ProductionOrderApi api = new ProductionOrderApi();

    
    /**
     * 
     *
     * Creates a new production order in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addProductionOrderTest() throws ApiException {
        ProductionOrderInput productionOrders = null;
        ProductionOrder response = api.addProductionOrder(productionOrders);

        // TODO: test validations
    }
    
    /**
     * Find Production order by ID
     *
     * Returns a single production order if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findProductionOrderByIdTest() throws ApiException {
        Long id = null;
        ProductionOrder response = api.findProductionOrderById(id);

        // TODO: test validations
    }
    
    /**
     * All production order
     *
     * Returns all production order from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findProductionOrdersTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<ProductionOrder> response = api.findProductionOrders(tags, limit);

        // TODO: test validations
    }
    
}
