/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.ProductVariant;
import io.swagger.client.model.ProductVariantInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductVariantApi
 */
@Ignore
public class ProductVariantApiTest {

    private final ProductVariantApi api = new ProductVariantApi();

    
    /**
     * 
     *
     * Creates a new product variant in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addProductVariantTest() throws ApiException {
        ProductVariantInput productVariants = null;
        ProductVariant response = api.addProductVariant(productVariants);

        // TODO: test validations
    }
    
    /**
     * Find Product variant by ID
     *
     * Returns a single product variant if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findProductVariantByIdTest() throws ApiException {
        Long id = null;
        ProductVariant response = api.findProductVariantById(id);

        // TODO: test validations
    }
    
    /**
     * All product variant
     *
     * Returns all product variant from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findProductVariantsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<ProductVariant> response = api.findProductVariants(tags, limit);

        // TODO: test validations
    }
    
}
