/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.SalesOrder;
import io.swagger.client.model.SalesOrderInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SalesOrderApi
 */
@Ignore
public class SalesOrderApiTest {

    private final SalesOrderApi api = new SalesOrderApi();

    
    /**
     * 
     *
     * Creates a new sales order in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSalesOrderTest() throws ApiException {
        SalesOrderInput salesOrders = null;
        SalesOrder response = api.addSalesOrder(salesOrders);

        // TODO: test validations
    }
    
    /**
     * All sales order
     *
     * Returns all sales order from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findSalesOrderTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<SalesOrder> response = api.findSalesOrder(tags, limit);

        // TODO: test validations
    }
    
    /**
     * Find Sales order by ID
     *
     * Returns a single sales order if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findSalesOrderByIdTest() throws ApiException {
        Long id = null;
        SalesOrder response = api.findSalesOrderById(id);

        // TODO: test validations
    }
    
}
