/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.StockLocation;
import io.swagger.client.model.StockLocationInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StockLocationApi
 */
@Ignore
public class StockLocationApiTest {

    private final StockLocationApi api = new StockLocationApi();

    
    /**
     * 
     *
     * Creates a new stock location in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addStockLocationTest() throws ApiException {
        StockLocationInput stockLocations = null;
        StockLocation response = api.addStockLocation(stockLocations);

        // TODO: test validations
    }
    
    /**
     * Find Stock location by ID
     *
     * Returns a single stock location if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findStockLocationByIdTest() throws ApiException {
        Long id = null;
        StockLocation response = api.findStockLocationById(id);

        // TODO: test validations
    }
    
    /**
     * All stock location
     *
     * Returns all stock location from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findStockLocationsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<StockLocation> response = api.findStockLocations(tags, limit);

        // TODO: test validations
    }
    
}
