/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.StockAdjustment;
import io.swagger.client.model.StockAdjustmentInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StockAdjustmentApi
 */
@Ignore
public class StockAdjustmentApiTest {

    private final StockAdjustmentApi api = new StockAdjustmentApi();

    
    /**
     * 
     *
     * Creates a new stock adjustment in the system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addStockAdjustmentTest() throws ApiException {
        StockAdjustmentInput stockAdjustments = null;
        StockAdjustment response = api.addStockAdjustment(stockAdjustments);

        // TODO: test validations
    }
    
    /**
     * Find Stock adjustment by ID
     *
     * Returns a single stock adjustment if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findStockAdjustmentByIdTest() throws ApiException {
        Long id = null;
        StockAdjustment response = api.findStockAdjustmentById(id);

        // TODO: test validations
    }
    
    /**
     * All stock adjustment
     *
     * Returns all stock adjustment from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findStockAdjustmentsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<StockAdjustment> response = api.findStockAdjustments(tags, limit);

        // TODO: test validations
    }
    
}
