/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.WorkCentre;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkCentreApi
 */
@Ignore
public class WorkCentreApiTest {

    private final WorkCentreApi api = new WorkCentreApi();

    
    /**
     * Find Work centre by ID
     *
     * Returns a single work centre if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findWorkCentreByIdTest() throws ApiException {
        Long id = null;
        WorkCentre response = api.findWorkCentreById(id);

        // TODO: test validations
    }
    
    /**
     * All work centre
     *
     * Returns all work centre from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findWorkCentresTest() throws ApiException {
        Long workCentreGroupId = null;
        List<String> tags = null;
        Integer limit = null;
        List<WorkCentre> response = api.findWorkCentres(workCentreGroupId, tags, limit);

        // TODO: test validations
    }
    
}
