/*
 * Beanie ERP API
 * An API specification for interacting with the Beanie ERP system
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@bean.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.WorkCentreGroup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkCentreGroupApi
 */
@Ignore
public class WorkCentreGroupApiTest {

    private final WorkCentreGroupApi api = new WorkCentreGroupApi();

    
    /**
     * Find Work centre group by ID
     *
     * Returns a single work centre group if the user has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findWorkCentreGroupByIdTest() throws ApiException {
        Long id = null;
        WorkCentreGroup response = api.findWorkCentreGroupById(id);

        // TODO: test validations
    }
    
    /**
     * All work centre group
     *
     * Returns all work centre group from the system that the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findWorkCentreGroupsTest() throws ApiException {
        List<String> tags = null;
        Integer limit = null;
        List<WorkCentreGroup> response = api.findWorkCentreGroups(tags, limit);

        // TODO: test validations
    }
    
}
